name: Build
on:
  push:
    branches:    
      - master 
  pull_request:
    branches:    
      - master   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14"]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Installing
        run: yarn install --frozen-lockfile
      - name: Linting
        run: yarn lint
      - name: UnitTesting
        run: yarn test:unit
      - name: TscIntegrationTesting
        run: yarn test:tsc-integration
      - name: JsiiIntegrationTesting  
        run: yarn test:jsii-integration
      - name: Anti-tamper check
        run: git diff --exit-code